name: 'Upload to SFS'
inputs:
  path:
    description: 'Build directory path'
    required: true
  token:
    required: true
  message:
    default: 'chore: publish artifacts'
    required: true

runs:
  using: "composite"
  steps:
      - name: Publish
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
          cd ${{ inputs.path }}

          git remote set-url origin https://${{ inputs.token }}@github.com/${{ inputs.repo }}.git
    
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "${{ inputs.message }}"
            git push origin main
          else
            echo "No changes to commit."
          fi
