name: 'Upload to SFS'
description: 'Build static-file-server pages'
inputs:
  path:
    description: 'Build directory path'
    required: true
  repo:
    description: 'Github repository'
    required: true

runs:
  using: "composite"
  steps:
      - name: Clone
        shell: bash
        run: |
          git clone --depth 1 https://github.com/${{ inputs.repo }} ${{ inputs.path }}/.tmp
          mv ${{ inputs.path }}/.tmp/* ${{ inputs.path }}
        
      - name: Publish
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
          cd ${{ inputs.path }}
    
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: publish artifacts for Stargate"
            git push origin main
          else
            echo "No changes to commit."
          fi
