name: 'Setup SFS'
inputs:
  path:
    description: 'Build directory path'
    required: true
    default: ${{ runner.temp }}/maven
  repo:
    description: 'Github repository'
    required: true

outputs:
  path: 
    value: ${{ inputs.path }}

runs:
  using: "composite"
  steps:
      - name: Clone
        id: setup
        shell: bash
        run: |
          git clone --depth 1 https://github.com/${{ inputs.repo }} ${{ inputs.path }}
          echo "SFS_REPO=${{ inputs.repo }}" >> $GITHUB_ENV
          echo "SFS_PATH=${{ inputs.path }}" >> $GITHUB_ENV
